### ISSUE TITLE
duckietown_map_publisher crashing

### ISSUE THREAD

**Issue by lgulich** [duckietown/duckietown-visualization#2]
We have changed our repo to the cookiecutter style and ever since are experiencing the following issue. The `duckietown_map_publisher` node keeps crashing on launch. The same error is also obtained when running the example.launch fromthe visualization_example package.

Do you know where this could come from?

```
Traceback (most recent call last):
  File "/home/lgulich/Documents/repos/duckietown/dt_catkin_ws/src/duckietown-mplan2/duckietown-fplan/src/duckietown-visualization/duckietown_visualization/src/publish_map.py", line 21, in <module>
    m = dw.load_map(map_name)
  File "/home/lgulich/Documents/repos/duckietown/duckietown-world/src/duckietown_world/world_duckietown/map_loading.py", line 84, in load_map
    return construct_map(yaml_data, tile_size)
  File "/home/lgulich/Documents/repos/duckietown/duckietown-world/src/duckietown_world/world_duckietown/map_loading.py", line 158, in construct_map
    for it in list(iterate_by_class(tm, Tile)):
  File "/home/lgulich/Documents/repos/duckietown/duckietown-world/src/duckietown_world/geo/measurements_utils.py", line 140, in iterate_by_class
    for _ in iterate_by_test(po, lambda _: isinstance(_, klass)):
  File "/home/lgulich/Documents/repos/duckietown/duckietown-world/src/duckietown_world/geo/measurements_utils.py", line 151, in iterate_by_test
    G = get_flattened_measurement_graph(po, include_root_to_self=True)
  File "/home/lgulich/Documents/repos/duckietown/duckietown-world/src/duckietown_world/geo/measurements_utils.py", line 117, in get_flattened_measurement_graph
    sr = v['attr_dict']['sr'].transform
KeyError: u'attr_dict'

[duckietown_map_publisher-5] process has died [pid 14797, exit code 1, cmd /home/lgulich/Documents/repos/duckietown/dt_catkin_ws/src/duckietown-mplan2/duckietown-fplan/src/duckietown-visualization/duckietown_visualization/src/publish_map.py __name:=duckietown_map_publisher __log:=/home/lgulich/.ros/log/e51c976e-0323-11e9-8e58-109adda451d5/duckietown_map_publisher-5.log].
log file: /home/lgulich/.ros/log/e51c976e-0323-11e9-8e58-109adda451d5/duckietown_map_publisher-5*.log
```

**Comment by lgulich** [comment]
Found the issue... duckietown-world requires networkx version 2.2 whereas the new cookiecutter template requires comptests which requires networkx 1.1 and has a different format for outputting graph's edges

Closing issue
