### ISSUE TITLE
None type object not tested

### ISSUE THREAD

**Issue by AmaurX** [duckietown/duckietown-visualization#3]
Issue I encountered @surirohit 

```Traceback (most recent call last):
  File "/graph_optimizer/catkin_ws/src/cslam_visualization/src/publish_markers.py", line 22, in <module>
    markers = utils.get_markers(duckiebots,watchtowers,apriltags,listener)
  File "/graph_optimizer/catkin_ws/src/cslam_visualization/include/cslam_visualization/utils.py", line 172, in get_markers
    marker_array.markers.append(get_trafficsign_marker(tag_id,trans[0],trans[1],rot,marker_type))
  File "/graph_optimizer/catkin_ws/src/cslam_visualization/include/cslam_visualization/utils.py", line 24, in get_trafficsign_marker
    "sign_" + marker_type.replace('-','_') + ".dae"
AttributeError: 'NoneType' object has no attribute 'replace'
```

**Comment by AmaurX** [comment]
my bad I did something stupid
